# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCode', models.CharField(max_length=10)),
                ('marketNo', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockinfo',
            unique_together=set([('reportCode', 'marketNo')]),
        ),
    ]
